import cv2
import numpy as np

VIDEO_PATH = "D:/Мисис/Диплом/AirVision/datasets/output.mp4"

FX = 615.0
FY = 615.0
CX = 320.0
CY = 240.0

CAMERA_MATRIX = np.array([[FX, 0, CX],
                          [0, FY, CY],
                          [0, 0, 1]
                          ], dtype=np.float64)

DIST_COEFFS = np.zeros((4,1), dtype=np.float64)

LOWE_RATIO = 0.9
KNN_K = 2

TRANSLATION_THRESHOLD = 0.25
ROTATION_THRESHOLD_DEG = 1.0
ROTATION_THRESHOLD = np.deg2rad(ROTATION_THRESHOLD_DEG)

TRIANGULATION_THRESHOLD_DEG = 1.5
TRIANGULATION_THRESHOLD = np.deg2rad(TRIANGULATION_THRESHOLD_DEG)

BUNDLE_ADJUSTMENT_FRAMES = 10
ORB_INTERVAL = 1
FORCE_KEYFRAME_INTERVAL = 6
KEYFRAME_BA_INTERVAL = 2

MAX_REPROJ_ERROR = 67
MIN_OBSERVATIONS = 2
MAX_POINTS = 10000

MAP_CLEAN_MAX_DISTANCE = 175

BA_MAX_NFEV = 100
BA_FTOL = 0.01
BA_XTOL = 0.003
BA_GTOL = 0.0015

E_RANSAC_THRESHOLD = 0.5
H_RANSAC_THRESHOLD = 0.1
HOMOGRAPHY_INLIER_RATIO = 0.99999999

# Параметры ре-инициализации
LOST_THRESHOLD = 5

EPIPOLAR_THRESHOLD = 0.035

INIT_SCALE = 1.0
ASSUMED_MEAN_DEPTH_DURING_INIT = 0.8

KPTS_UNIFORM_SELECTION_GRID_SIZE = 15
MAX_PTS_PER_GRID = 8
MAX_TOTAL_POINTS = 90000

RADIO_THRESH = 0.3

